import { describe, expect, it } from "vitest";
import {
  diffCounts,
  diffLineCounts,
  GITHUB_PR_BODY_LIMIT,
  MAX_DIFF_CHARS,
  MAX_DIFF_LINES,
  truncateForGithub,
  unifiedDiff,
  upgradePrBody,
  upgradePrTitle,
} from "../src/upgrade/pr-body.js";
import type { UpgradeReport } from "../src/upgrade/types.js";

function report(overrides: Partial<UpgradeReport> = {}): UpgradeReport {
  return {
    fromVersion: "1.0.7",
    toVersion: "1.0.8",
    framework: "vite",
    notes: [],
    files: [],
    skippedFiles: [],
    dependencies: [],
    keptDependencies: [],
    migrations: [],
    commits: [],
    changelogUrl: "",
    ...overrides,
  };
}

describe("upgradePrTitle", () => {
  it("keeps the conventional title with the target version", () => {
    expect(upgradePrTitle(report({ toVersion: "1.2.0" }))).toBe(
      "chore: upgrade raulmoracode-create to 1.2.0",
    );
  });
});

describe("upgradePrBody structure", () => {
  it("renders every section for an empty plan", () => {
    const body = upgradePrBody(report());
    expect(
      body.startsWith("# Upgrade raulmoracode-create 1.0.7 → 1.0.8\n"),
    ).toBe(true);
    expect(body.endsWith("\n")).toBe(true);
    for (const heading of [
      "## Summary",
      "## Changes by version",
      "## Dependencies",
      "## Migrations",
      "## Action items",
      "## Not touched",
      "## Commits",
    ]) {
      expect(body).toContain(heading);
    }
    expect(body).not.toContain("## ⚠️ Overwritten files with local changes");
    expect(body).toContain("_No release between the two versions");
    expect(body).toContain("_No dependency changed._");
    expect(body).toContain("_No migration had to be applied._");
    expect(body).toContain("_No commits were recorded for this upgrade._");
    expect(body).toContain("- Application code under `src/`");
    expect(body).toContain("- `README.md`");
    expect(body).toContain("- `CHANGELOG.md`");
    expect(body).toContain("- `LICENSE`");
    expect(body).toContain(
      "Generated by `raulmoracode-create` `upgrade` (v1.0.8).",
    );
    expect(body).not.toContain("Changelog:");
  });

  it("keeps the section order", () => {
    const body = upgradePrBody(
      report({
        files: [
          {
            path: "biome.json",
            status: "overwritten",
            previousContent: '{\n  "a": 1\n}\n',
            nextContent: '{\n  "a": 2\n}\n',
          },
        ],
        notes: [
          {
            version: "1.0.8",
            summary: "Biome config update",
            changes: [
              {
                files: ["biome.json"],
                what: "Biome 2.5.14 rules",
                why: "New lints in 2.5",
                action: "Run `pnpm check`",
              },
            ],
          },
        ],
        dependencies: [
          {
            name: "vite",
            type: "devDependencies",
            from: "8.3.0",
            to: "8.3.1",
            hadLocalVersion: false,
          },
        ],
        migrations: [
          {
            id: "migrate-biome-schema",
            version: "1.0.8",
            description: "Move assist actions",
            why: "Biome 2 schema change",
          },
        ],
        commits: ["abc1234 chore: upgrade"],
        changelogUrl:
          "https://github.com/raulmoracode/create/releases/tag/v1.0.8",
      }),
    );
    const order = [
      "# Upgrade",
      "## Summary",
      "## ⚠️ Overwritten files with local changes",
      "## Changes by version",
      "## Dependencies",
      "## Migrations",
      "## Action items",
      "## Not touched",
      "## Commits",
      "Generated by",
    ];
    let previous = -1;
    for (const marker of order) {
      const index = body.indexOf(marker);
      expect(index).toBeGreaterThan(previous);
      previous = index;
    }
    expect(body).toContain(
      "Changelog: https://github.com/raulmoracode/create/releases/tag/v1.0.8",
    );
    expect(body).toContain("1. abc1234 chore: upgrade");
  });

  it("counts every file status, skipped files, dependencies and migrations", () => {
    const body = upgradePrBody(
      report({
        files: [
          {
            path: "a",
            status: "updated",
            previousContent: "1\n",
            nextContent: "2\n",
          },
          {
            path: "b",
            status: "new",
            previousContent: null,
            nextContent: "2\n",
          },
          {
            path: "c",
            status: "overwritten",
            previousContent: "1\n",
            nextContent: "2\n",
          },
          {
            path: "d",
            status: "removed",
            previousContent: "1\n",
            nextContent: null,
          },
        ],
        skippedFiles: [{ path: "e", reason: "deleted-locally" }],
        dependencies: [
          {
            name: "husky",
            type: "devDependencies",
            from: null,
            to: "9.1.7",
            hadLocalVersion: true,
          },
          {
            name: "commitlint",
            type: "devDependencies",
            from: "19.8.1",
            to: "19.8.2",
            hadLocalVersion: false,
          },
        ],
        keptDependencies: [
          { name: "vitest", pinned: "3.2.4", reason: "removed-locally" },
        ],
        migrations: [
          { id: "m1", version: "1.0.8", description: "d", why: "w" },
        ],
      }),
    );
    expect(body).toContain("| Files updated | 1 |");
    expect(body).toContain("| Files new | 1 |");
    expect(body).toContain("| Files overwritten with local changes | 1 |");
    expect(body).toContain("| Files removed | 1 |");
    expect(body).toContain("| Files skipped | 1 |");
    expect(body).toContain("| Dependencies updated | 2 |");
    expect(body).toContain("| Dependencies kept as-is | 1 |");
    expect(body).toContain("| Migrations applied | 1 |");
    expect(body).toContain(
      "> 1 file(s) had local changes and were overwritten.",
    );
    expect(body).toContain(
      "| husky | devDependencies | — | 9.1.7 | had a local version |",
    );
    expect(body).toContain(
      "| commitlint | devDependencies | 19.8.1 | 19.8.2 | — |",
    );
    expect(body).toContain("### Kept as-is");
    expect(body).toContain("| vitest | 3.2.4 | removed-locally |");
  });
});

describe("overwritten files section", () => {
  it("documents the matched note, the diff and the recovery hint", () => {
    const body = upgradePrBody(
      report({
        files: [
          {
            path: "biome.json",
            status: "overwritten",
            previousContent: '{\n  "a": 1\n}\n',
            nextContent: '{\n  "a": 2\n}\n',
          },
        ],
        notes: [
          {
            version: "1.0.8",
            summary: "s",
            changes: [
              {
                files: ["biome.json"],
                what: "What happened",
                why: "Why it happened",
                action: "What to do",
              },
            ],
          },
        ],
      }),
    );
    expect(body).toContain("- **What**: What happened");
    expect(body).toContain("- **Why**: Why it happened");
    expect(body).toContain("- **Action**: What to do");
    expect(body).toContain("```diff");
    expect(body).toContain('-  "a": 1');
    expect(body).toContain('+  "a": 2');
    expect(body).toContain(
      "Re-apply your customizations to `biome.json` in this branch; the overwritten version is isolated in its own commit.",
    );
  });

  it("says explicitly when no upgrade note matches the file", () => {
    const body = upgradePrBody(
      report({
        files: [
          {
            path: "vite.config.ts",
            status: "overwritten",
            previousContent: "a\n",
            nextContent: "b\n",
          },
        ],
        notes: [
          {
            version: "1.0.8",
            summary: "s",
            changes: [{ files: ["biome.json"], what: "w", why: "y" }],
          },
        ],
      }),
    );
    expect(body).toContain(
      "- _No upgrade note for this file: it was updated as part of the upgrade but no release note describes it._",
    );
  });

  it("falls back to a placeholder when there is no content diff", () => {
    const body = upgradePrBody(
      report({
        files: [
          {
            path: "x.json",
            status: "overwritten",
            previousContent: "same\n",
            nextContent: "same\n",
          },
        ],
      }),
    );
    expect(body).toContain("_No content changes recorded for this file._");
  });
});

describe("changes by version", () => {
  it("sorts versions ascending and lists the action bullets", () => {
    const body = upgradePrBody(
      report({
        notes: [
          {
            version: "1.1.0",
            summary: "Newer",
            changes: [
              {
                files: ["b.ts"],
                what: "w2",
                why: "y2",
                action: "Action two",
              },
            ],
          },
          {
            version: "1.0.8",
            summary: "Older",
            changes: [
              {
                files: ["a.ts", "c.ts"],
                what: "w1",
                why: "y1",
              },
              { files: [], what: "w0", why: "y0", action: "Action zero" },
            ],
          },
        ],
      }),
    );
    expect(body.indexOf("### 1.0.8")).toBeLessThan(body.indexOf("### 1.1.0"));
    expect(body).toContain("| a.ts | — | — | w1 | y1 |");
    expect(body).toContain("| c.ts | — | — | w1 | y1 |");
    expect(body).toContain("| — | — | — | w0 | y0 |");
    expect(body).toContain("- Action zero");
    expect(body).toContain("- Action two");
  });

  it("shows the status and the +/− line counts for known files", () => {
    const body = upgradePrBody(
      report({
        notes: [
          {
            version: "1.0.8",
            summary: "s",
            changes: [{ files: ["biome.json"], what: "w", why: "y" }],
          },
        ],
        files: [
          {
            path: "biome.json",
            status: "updated",
            previousContent: "a\nb\n",
            nextContent: "a\n",
          },
        ],
      }),
    );
    expect(body).toContain("| biome.json | updated | +0 −1 | w | y |");
  });
});

describe("escaping and line endings", () => {
  it("escapes pipes and folds newlines in table cells", () => {
    const body = upgradePrBody(
      report({
        notes: [
          {
            version: "1.0.8",
            summary: "s",
            changes: [{ files: ["a|b.ts"], what: "w|1", why: "line1\nline2" }],
          },
        ],
      }),
    );
    expect(body).toContain("| a\\|b.ts | — | — | w\\|1 | line1<br>line2 |");
  });

  it("normalises CRLF before diffing", () => {
    const diff = unifiedDiff("a\r\nb\r\n", "a\nb\n");
    expect(diff).toBe("");
    const body = upgradePrBody(
      report({
        files: [
          {
            path: "x.ts",
            status: "overwritten",
            previousContent: "a\r\nb\r\n",
            nextContent: "a\r\nc\r\n",
          },
        ],
      }),
    );
    expect(body).toContain("-b");
    expect(body).toContain("+c");
    expect(body).not.toContain("\r");
  });
});

describe("unifiedDiff", () => {
  it("returns an empty string when the content is identical", () => {
    expect(unifiedDiff("a\nb\n", "a\nb\n")).toBe("");
    expect(unifiedDiff(null, null)).toBe("");
  });

  it("diffs a single changed line", () => {
    const diff = unifiedDiff("a\nb\nc\n", "a\nB\nc\n");
    expect(diff.split("\n")).toEqual([
      "@@ -1,3 +1,3 @@",
      " a",
      "-b",
      "+B",
      " c",
    ]);
  });

  it("diffs insertions and deletions", () => {
    expect(unifiedDiff("a\nc\n", "a\nb\nc\nd\n")).toBe(
      "@@ -1,2 +1,4 @@\n a\n+b\n c\n+d",
    );
    expect(unifiedDiff("a\nb\nc\n", "a\nc\n")).toBe(
      "@@ -1,3 +1,2 @@\n a\n-b\n c",
    );
  });

  it("counts added and removed lines", () => {
    expect(diffLineCounts("a\nb\n", "a\n")).toEqual({ added: 0, removed: 1 });
    expect(diffLineCounts("a\n", "a\nb\n")).toEqual({ added: 1, removed: 0 });
    expect(diffLineCounts("a\nb\nc\n", "a\nB\nc\n")).toEqual({
      added: 1,
      removed: 1,
    });
    expect(diffCounts("a\nb\nc\n", "a\nB\nc\n")).toBe("+1 −1");
    expect(diffCounts(null, "x\n")).toBe("+1 −0");
    expect(diffCounts("x\n", null)).toBe("+0 −1");
    expect(diffCounts("a\n", "a\n")).toBe("+0 −0");
  });

  it("caps very large files", () => {
    const previous = Array.from(
      { length: MAX_DIFF_LINES + 50 },
      (_, i) => `l${i}`,
    );
    const next = Array.from({ length: MAX_DIFF_LINES + 50 }, (_, i) => `m${i}`);
    const diff = unifiedDiff(
      `${previous.join("\n")}\n`,
      `${next.join("\n")}\n`,
    );
    expect(diff).toContain("diff truncated to the first");
    expect(diff.split("\n").length).toBeLessThanOrEqual(MAX_DIFF_LINES * 2 + 2);
    expect(diff.length).toBeLessThan(MAX_DIFF_CHARS);

    const wide = Array.from(
      { length: 300 },
      (_, i) => `line ${i} ${"x".repeat(200)}`,
    );
    const wideNext = wide.map((line) => `${line} changed`);
    const wideDiff = unifiedDiff(
      `${wide.join("\n")}\n`,
      `${wideNext.join("\n")}\n`,
    );
    expect(wideDiff).toContain("diff truncated (");
    expect(wideDiff.length).toBeLessThan(MAX_DIFF_CHARS + 200);
  });
});

describe("action items", () => {
  it("asks to review overwritten files, run biome, tests and CI", () => {
    const body = upgradePrBody(
      report({
        files: [
          {
            path: "biome.json",
            status: "overwritten",
            previousContent: "a\n",
            nextContent: "b\n",
          },
          {
            path: "vitest.config.ts",
            status: "updated",
            previousContent: "a\n",
            nextContent: "b\n",
          },
          {
            path: ".github/workflows/ci.yml",
            status: "updated",
            previousContent: "a\n",
            nextContent: "b\n",
          },
        ],
      }),
    );
    expect(body).toContain(
      "- [ ] Re-apply or drop the local customizations of every overwritten file listed in the ⚠️ section.",
    );
    expect(body).toContain(
      "- [ ] Run `pnpm check` (Biome config and hooks may have changed).",
    );
    expect(body).toContain(
      "- [ ] Run `pnpm test` and make sure the suite still passes.",
    );
    expect(body).toContain(
      "- [ ] Verify the CI workflow runs green on this branch.",
    );
    expect(body).toContain(
      "- [ ] Delete nothing else: this branch only touches files managed by `raulmoracode-create`.",
    );
  });

  it("derives action items from the notes actions", () => {
    const body = upgradePrBody(
      report({
        notes: [
          {
            version: "1.0.8",
            summary: "s",
            changes: [
              {
                files: ["a"],
                what: "w",
                why: "y",
                action: "Migrate the theme",
              },
            ],
          },
          {
            version: "1.0.9",
            summary: "s",
            changes: [
              {
                files: ["b"],
                what: "w",
                why: "y",
                action: "Migrate the theme",
              },
            ],
          },
        ],
      }),
    );
    expect(body.match(/- \[ \] Migrate the theme/g)).toHaveLength(1);
    expect(body).toContain(
      "- [ ] Review the whole diff of this pull request before merging.",
    );
    expect(body).not.toContain("- [ ] Run `pnpm check`");
    expect(body).not.toContain("- [ ] Run `pnpm test`");
  });
});

describe("truncateForGithub", () => {
  function hugeReport(fileCount: number): UpgradeReport {
    const lines = Array.from(
      { length: 200 },
      (_, i) => `line ${i} ${"y".repeat(60)}`,
    );
    return report({
      files: Array.from({ length: fileCount }, (_, index) => ({
        path: `file-${index}.json`,
        status: "overwritten" as const,
        previousContent: `${lines.join("\n")}\n`,
        nextContent: `${lines.map((line) => `${line} changed`).join("\n")}\n`,
      })),
      notes: [
        {
          version: "1.0.8",
          summary: "s",
          changes: [
            {
              files: Array.from(
                { length: fileCount },
                (_, index) => `file-${index}.json`,
              ),
              what: "Regenerated",
              why: "New template",
            },
          ],
        },
      ],
    });
  }

  it("keeps short bodies untouched", () => {
    const body = upgradePrBody(report());
    expect(truncateForGithub(body)).toBe(body);
  });

  it("trims diffs and keeps summary, warning section, tables and action items", () => {
    const body = upgradePrBody(hugeReport(60));
    expect(body.length).toBeGreaterThan(GITHUB_PR_BODY_LIMIT);
    const truncated = truncateForGithub(body);
    expect(truncated.length).toBeLessThanOrEqual(GITHUB_PR_BODY_LIMIT);
    expect(truncated).toContain("## Summary");
    expect(truncated).toContain("## ⚠️ Overwritten files with local changes");
    expect(truncated).toContain("| File | Status | +/− lines | What | Why |");
    expect(truncated).toContain("## Dependencies");
    expect(truncated).toContain("## Action items");
    expect(truncated).toContain("| Count | Value |");
    expect(truncated).toContain("Some inline diffs were trimmed");
    expect(truncated).toContain("**Files changed** tab");
    expect(truncated).not.toContain("```diff");
  });

  it("is idempotent", () => {
    const body = upgradePrBody(hugeReport(60));
    const once = truncateForGithub(body);
    expect(truncateForGithub(once)).toBe(once);
    expect(truncateForGithub(truncateForGithub(once))).toBe(once);
  });

  it("collapses before dropping diffs", () => {
    const body = upgradePrBody(hugeReport(12));
    expect(body.length).toBeGreaterThan(GITHUB_PR_BODY_LIMIT);
    const collapsed = truncateForGithub(body);
    expect(collapsed.length).toBeLessThanOrEqual(GITHUB_PR_BODY_LIMIT);
    expect(collapsed).not.toContain("```diff");
  });

  it("appends the note when the anchor is missing", () => {
    const long = `${"x".repeat(GITHUB_PR_BODY_LIMIT)}\n\nend`;
    const truncated = truncateForGithub(long);
    expect(truncated).toContain("Some inline diffs were trimmed");
    expect(truncateForGithub(truncated)).toBe(truncated);
  });
});
