import { RAULMORACODE_REGISTRY_ADD_EXAMPLE } from "./components.js";

export function agentsMd(): string {
  return [
    "# AGENTS.md",
    "",
    "## Project guidelines",
    "",
    "This project was initially generated with `@raulmoracode/create`.",
    "",
    "Treat the current repository state as the source of truth. Do not assume that the original scaffold configuration, dependencies, scripts, or architecture are still unchanged.",
    "",
    "Before making changes, inspect the existing codebase and its configuration.",
    "",
    "## General principles",
    "",
    "- Follow existing project conventions and patterns.",
    "- Prefer simple, focused solutions over unnecessary abstractions.",
    "- Reuse existing components, utilities, hooks, and patterns when appropriate.",
    "- Avoid duplicating functionality that already exists.",
    "- Keep changes scoped to the requested task.",
    "- Do not modify unrelated files.",
    "- Preserve existing user changes.",
    "- Do not introduce a new library when the existing project can reasonably solve the problem.",
    "- Do not remove or replace existing dependencies without a clear reason.",
    "- Do not reintroduce dependencies that have been intentionally removed.",
    "",
    "## Dependencies and configuration",
    "",
    "Always inspect the current `package.json` before using or adding a dependency.",
    "",
    "Do not assume that a dependency is installed because it may have been included in the original scaffold.",
    "",
    "Treat the following files as sources of truth for the current project configuration:",
    "",
    "- `package.json`",
    "- `pnpm-lock.yaml`",
    "- `tsconfig.json`",
    "- `biome.json`",
    "- `components.json`",
    "- `.nvmrc`",
    "- framework-specific configuration files",
    "",
    "Use the package manager already configured by the project.",
    "",
    "Do not change package managers unless explicitly requested.",
    "",
    "## Project tooling",
    "",
    "This project uses pnpm exclusively. Never use npm or yarn.",
    "",
    "Available scripts (see `package.json` for the full list):",
    "",
    "- `pnpm dev` — start the development server.",
    "- `pnpm build` — create a production build.",
    "- `pnpm test` — run the test suite.",
    "- `pnpm check` — run the formatter and linter check.",
    "- `pnpm format` — apply formatting.",
    "- `pnpm lint` — run the linter.",
    "",
    "UI components come from shadcn. Add new components with:",
    "",
    "```bash",
    RAULMORACODE_REGISTRY_ADD_EXAMPLE,
    "```",
    "",
    "Browse the catalogue at https://registry.raulmoracode.com.",
    "",
    "Do not hand-write component files under the shadcn UI directory. Follow `components.json`, including the `@raulmoracode` registry.",
    "",
    "## Code style",
    "",
    "Follow the existing code style and project structure.",
    "",
    "Use the project's configured formatter and linter.",
    "",
    "Do not introduce ESLint, Prettier, or another formatting/linting system when an existing project tool already provides that functionality, unless explicitly requested.",
    "",
    "Prefer readable and maintainable code over clever implementations.",
    "",
    "Avoid unnecessary comments. Add comments when they explain a non-obvious decision or constraint.",
    "",
    "## Components and UI",
    "",
    "Before creating a new component, check whether an existing component already provides the required functionality.",
    "",
    "Prefer composition and reuse over duplicated UI implementations.",
    "",
    "If the project uses shadcn, follow the existing shadcn configuration and component conventions.",
    "",
    "Do not manually recreate a component when an appropriate existing project component can be reused.",
    "",
    "## Architecture",
    "",
    "Follow the architecture already present in the repository.",
    "",
    "Do not introduce a new architectural pattern solely because it is personally preferred.",
    "",
    "When adding functionality:",
    "",
    "1. Identify the existing pattern used for similar functionality.",
    "2. Follow that pattern when appropriate.",
    "3. Keep the implementation close to the relevant feature.",
    "4. Avoid creating generic abstractions before they are actually needed.",
    "",
    "For framework-specific behavior, follow the conventions of the framework version currently installed in the project.",
    "",
    "## Validation",
    "",
    "Inspect `package.json` to determine the available scripts before running commands.",
    "",
    "After making changes, run the most relevant validation commands for the affected code.",
    "",
    "For substantial changes, prefer running:",
    "",
    "```bash",
    "pnpm check",
    "pnpm test",
    "pnpm build",
    "```",
    "",
    "Do not claim that a change is complete if the relevant validation has not been performed.",
    "",
    "If a validation command fails because of an unrelated pre-existing problem, distinguish that from problems introduced by the current change.",
    "",
    "## Git",
    "",
    "Never use destructive Git commands unless explicitly requested.",
    "",
    "Do not use:",
    "",
    "```bash",
    "git push --force",
    "git push -f",
    "git reset --hard",
    "git clean -fd",
    "```",
    "",
    "Do not rewrite existing history unnecessarily.",
    "",
    "Do not discard or overwrite uncommitted user changes.",
    "",
    "Before modifying files, be aware of the current Git state when relevant.",
    "",
    "Do not commit changes unless explicitly requested.",
    "",
    "## Git hooks and commits",
    "",
    "Husky manages the Git hooks.",
    "",
    "`pre-commit` runs:",
    "",
    "```bash",
    "pnpm check",
    "pnpm test",
    "```",
    "",
    "`commit-msg` runs Commitlint.",
    "",
    "Commits must follow Conventional Commits.",
    "",
    "Valid commit examples:",
    "",
    "```text",
    "feat: add user profile",
    "fix: handle invalid input",
    "refactor: extract API client",
    "test: add query client tests",
    "docs: update project guide",
    "chore: update dependencies",
    "```",
    "",
    "Do not bypass hooks with `--no-verify` unless explicitly requested.",
    "",
    "Keep the project passing:",
    "",
    "```bash",
    "pnpm check",
    "pnpm test",
    "pnpm build",
    "```",
    "",
    "## Security",
    "",
    "Do not expose, commit, or hard-code secrets, API keys, access tokens, passwords, or credentials.",
    "",
    "Never replace environment variables with hard-coded credentials.",
    "",
    "Treat `.env` and other environment-specific files as sensitive.",
    "",
    "Do not weaken existing security mechanisms merely to make a task easier.",
    "",
    "## Dependency changes",
    "",
    "Before adding a dependency:",
    "",
    "1. Check whether the functionality already exists in the project.",
    "2. Check whether an existing dependency can provide it.",
    "3. Consider whether the dependency is actually necessary.",
    "4. Use the package manager configured by the project.",
    "5. Keep dependency versions consistent with the project's existing conventions.",
    "",
    "Avoid adding dependencies for trivial functionality that can be implemented safely with the existing stack.",
    "",
    "## Working with existing code",
    "",
    "Do not rewrite working code unnecessarily.",
    "",
    "Prefer the smallest change that correctly solves the requested problem.",
    "",
    "When modifying existing functionality, preserve its current behavior unless the task explicitly requires changing it.",
    "",
    "If the requested change conflicts with an existing architectural decision, inspect the relevant code and configuration before deciding how to proceed.",
    "",
    "## Template updates",
    "",
    "`raulmoracode.json` records the CLI version that created this project and the template migrations already applied.",
    "",
    "To apply the template migrations this project is missing:",
    "",
    "```bash",
    "pnpm dlx @raulmoracode/create@latest migrate --dry-run",
    "pnpm dlx @raulmoracode/create@latest migrate",
    "```",
    "",
    "The command never prompts and never commits: review the result with `git diff` and commit it yourself.",
    "",
    "## Final response",
    "",
    "When completing a task, briefly report:",
    "",
    "- What was changed.",
    "- Which files were modified.",
    "- What validation was performed.",
    "- Any relevant issues or limitations that remain.",
    "",
    "Do not claim tests, builds, or other commands were executed if they were not actually run.",
    "",
  ].join("\n");
}
