export function pullRequestTemplate(): string {
  return [
    "## Summary",
    "",
    "<!-- Briefly describe what this PR does and why. -->",
    "",
    "## Changes",
    "",
    "- ",
    "",
    "## How to test",
    "",
    "1. ",
    "2. ",
    "",
    "## Validation",
    "",
    "- [ ] `pnpm check`",
    "- [ ] `pnpm test`",
    "- [ ] `pnpm build`",
    "",
    "## Breaking changes",
    "",
    '<!-- List any breaking changes, or write "None". -->',
    "",
    "None",
    "",
  ].join("\n");
}
